name: Build macOS ARM64

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-14

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'
        architecture: 'arm64'

    - name: Check Python version and architecture
      run: |
        python --version
        python -c "import platform; print(f'Architecture: {platform.machine()}')"

    - name: Install system dependencies
      run: |
        brew update
        brew install create-dmg
        brew install iconutil

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade setuptools wheel
        pip install -r requirements.txt
        pip list

    - name: Prepare build environment
      run: |
        mkdir -p dist
        mkdir -p build
        ls -la

    - name: Build application
      run: |
        chmod +x build_mac_arm64.sh
        ./build_mac_arm64.sh
      env:
        PYTHONPATH: ${{ github.workspace }}
        
    - name: Check build artifacts
      run: |
        ls -la dist/
        ls -la build/

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: mac-arm64-dmg
        path: dist/简历匹配分析工具-arm64.dmg
        if-no-files-found: error

    - name: Create Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: dist/简历匹配分析工具-arm64.dmg
        name: Release ${{ github.ref_name }}
        body: |
          macOS ARM64 (Apple Silicon) 版本
          
          ### 更新内容
          - 添加 Apple Silicon 原生支持
          - 优化性能和兼容性
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 