name: Build Application

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  release:
    types: [created]

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
        pip install PySide6==6.6.1
        pip install openai==1.12.0
        pip install PyPDF2==3.0.1
        pip install python-docx==1.1.0
        pip install pandas==2.2.0
        pip install openpyxl==3.1.2
    
    - name: Build with PyInstaller
      run: |
        pyinstaller --clean --name "简历匹配分析" --windowed --onefile --add-data "settings.json;." --add-data "job_history.json;." resume_matching_app_pyside6.py
    
    - name: Upload Windows artifact
      uses: actions/upload-artifact@v2
      with:
        name: Windows-Build
        path: dist/简历匹配分析.exe

  build-macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
        pip install PySide6==6.6.1
        pip install openai==1.12.0
        pip install PyPDF2==3.0.1
        pip install python-docx==1.1.0
        pip install pandas==2.2.0
        pip install openpyxl==3.1.2
    
    - name: Build with PyInstaller
      run: |
        pyinstaller --clean --name "简历匹配分析" --windowed --onefile --add-data "settings.json:." --add-data "job_history.json:." resume_matching_app_pyside6.py
    
    - name: Create DMG
      run: |
        cd dist
        mkdir -p dmg
        mv "简历匹配分析.app" dmg/
        hdiutil create -volname "简历匹配分析" -srcfolder dmg -ov -format UDZO "简历匹配分析.dmg"
    
    - name: Upload macOS artifact
      uses: actions/upload-artifact@v2
      with:
        name: macOS-Build
        path: dist/简历匹配分析.dmg

  create-release:
    needs: [build-windows, build-macos]
    runs-on: ubuntu-latest
    if: github.event_name == 'release' && github.event.action == 'created'
    
    steps:
    - name: Download all artifacts
      uses: actions/download-artifact@v2
    
    - name: Upload Release Assets
      uses: softprops/action-gh-release@v1
      with:
        files: |
          Windows-Build/简历匹配分析.exe
          macOS-Build/简历匹配分析.dmg
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 