name: Build Windows Executable

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write
  packages: write

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller
        pip install PySide6==6.6.1 PySide6-Essentials==6.6.1 PySide6-Addons==6.6.1 shiboken6==6.6.1
    
    - name: Build executable
      run: |
        dir
        python -c "import sys; print(sys.path)"
        pyinstaller build_windows.spec
    
    - name: List build output
      run: |
        dir dist
    
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: dist/简历匹配分析工具.exe
        tag_name: win-v${{ github.run_number }}
        name: Windows Release v${{ github.run_number }}
        draft: false
        prerelease: false 