name: Build macOS Application

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write
  packages: write

jobs:
  build:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller
        pip install PySide6==6.6.1 PySide6-Essentials==6.6.1 PySide6-Addons==6.6.1 shiboken6==6.6.1
    
    - name: Build application for Intel
      env:
        ARCHFLAGS: "-arch x86_64"
        MACOSX_DEPLOYMENT_TARGET: "10.15"
      run: |
        ls -la
        python -c "import sys; print(sys.path)"
        python -c "import platform; print(platform.machine())"
        pyinstaller build_mac.spec --target-arch x86_64
        ls -la dist
        cd dist
        ls -la
    
    - name: Compress application
      run: |
        cd dist
        zip -r 简历匹配分析工具-macOS-Intel.zip 简历匹配分析工具.app
        ls -la
    
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: macOS-Intel-App
        path: dist/简历匹配分析工具-macOS-Intel.zip
    
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: mac-intel-v${{ github.run_number }}
        release_name: macOS (Intel) Release v${{ github.run_number }}
        draft: false
        prerelease: false
    
    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./dist/简历匹配分析工具-macOS-Intel.zip
        asset_name: 简历匹配分析工具-macOS-Intel.zip
        asset_content_type: application/zip 